In [1]:
import pandas as pd 
import numpy as np


In [2]:
data=pd.read_csv("breast-cancer.csv")

In [3]:
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M     1.097064     -2.073335        1.269934   0.984375   
1           M     1.829821     -0.353632        1.685955   1.908708   
2           M     1.579888      0.456187        1.566503   1.558884   
3           M    -0.768909      0.253732       -0.592687  -0.764464   
4           M     1.750297     -1.151816        1.776573   1.826229   
..        ...          ...           ...             ...        ...   
564         M     2.110995      0.721473        2.060786   2.343856   
565         M     1.704854      2.085134        1.615931   1.723842   
566         M     0.702284      2.045574        0.672676   0.577953   
567         M     1.838341      2.336457        1.982524   1.735218   
568         B    -1.808401      1.221792       -1.814389  -1.347789   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           1.568466          3.283515        2.652874             2.532475   
1          -0.826962         -0.487072       -0.023846             0.548144   
2           0.942210          1.052926        1.363478             2.037231   
3           3.283553          3.402909        1.915897             1.451707   
4           0.280372          0.539340        1.371011             1.428493   
..               ...               ...             ...                  ...   
564         1.041842          0.219060        1.947285             2.320965   
565         0.102458         -0.017833        0.693043             1.263669   
566        -0.840484         -0.038680        0.046588             0.105777   
567         1.525767          3.272144        3.296944             2.658866   
568        -3.112085         -1.150752       -1.114873            -1.261820   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         2.217515  ...      1.886690      -1.359293         2.303601   
1         0.001392  ...      1.805927      -0.369203         1.535126   
2         0.939685  ...      1.511870      -0.023974         1.347475   
3         2.867383  ...     -0.281464       0.133984        -0.249939   
4        -0.009560  ...      1.298575      -1.466770         1.338539   
..             ...  ...           ...            ...              ...   
564      -0.312589  ...      1.901185       0.117700         1.752563   
565      -0.217664  ...      1.536720       2.047399         1.421940   
566      -0.809117  ...      0.561361       1.374854         0.579001   
567       2.137194  ...      1.961239       2.237926         2.303601   
568      -0.820070  ...     -1.410893       0.764190        -1.432735   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2.001237          1.307686           2.616665         2.109526   
1      1.890489         -0.375612          -0.430444        -0.146749   
2      1.456285          0.527407           1.082932         0.854974   
3     -0.550021          3.394275           3.893397         1.989588   
4      1.220724          0.220556          -0.313395         0.613179   
..          ...               ...                ...              ...   
564    2.015301          0.378365          -0.273318         0.664512   
565    1.494959         -0.691230          -0.394820         0.236573   
566    0.427906         -0.809587           0.350735         0.326767   
567    1.653171          1.430427           3.904848         3.197605   
568   -1.075813         -1.859019          -1.207552        -1.305831   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                2.296076        2.750622                 1.937015  
1                1.087084       -0.243890                 0.281190  
2                1.955000        1.152255                 0.201391  
3                2.175786        6.046041                 4.935010  
4                0.729259       -0.868353                -0.397100  
..                    ...         

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["diagnosis"]=le.fit_transform(data["diagnosis"])

In [7]:
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1     1.097064     -2.073335        1.269934   0.984375   
1            1     1.829821     -0.353632        1.685955   1.908708   
2            1     1.579888      0.456187        1.566503   1.558884   
3            1    -0.768909      0.253732       -0.592687  -0.764464   
4            1     1.750297     -1.151816        1.776573   1.826229   
..         ...          ...           ...             ...        ...   
564          1     2.110995      0.721473        2.060786   2.343856   
565          1     1.704854      2.085134        1.615931   1.723842   
566          1     0.702284      2.045574        0.672676   0.577953   
567          1     1.838341      2.336457        1.982524   1.735218   
568          0    -1.808401      1.221792       -1.814389  -1.347789   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           1.568466          3.283515        2.652874             2.532475   
1          -0.826962         -0.487072       -0.023846             0.548144   
2           0.942210          1.052926        1.363478             2.037231   
3           3.283553          3.402909        1.915897             1.451707   
4           0.280372          0.539340        1.371011             1.428493   
..               ...               ...             ...                  ...   
564         1.041842          0.219060        1.947285             2.320965   
565         0.102458         -0.017833        0.693043             1.263669   
566        -0.840484         -0.038680        0.046588             0.105777   
567         1.525767          3.272144        3.296944             2.658866   
568        -3.112085         -1.150752       -1.114873            -1.261820   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         2.217515  ...      1.886690      -1.359293         2.303601   
1         0.001392  ...      1.805927      -0.369203         1.535126   
2         0.939685  ...      1.511870      -0.023974         1.347475   
3         2.867383  ...     -0.281464       0.133984        -0.249939   
4        -0.009560  ...      1.298575      -1.466770         1.338539   
..             ...  ...           ...            ...              ...   
564      -0.312589  ...      1.901185       0.117700         1.752563   
565      -0.217664  ...      1.536720       2.047399         1.421940   
566      -0.809117  ...      0.561361       1.374854         0.579001   
567       2.137194  ...      1.961239       2.237926         2.303601   
568      -0.820070  ...     -1.410893       0.764190        -1.432735   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2.001237          1.307686           2.616665         2.109526   
1      1.890489         -0.375612          -0.430444        -0.146749   
2      1.456285          0.527407           1.082932         0.854974   
3     -0.550021          3.394275           3.893397         1.989588   
4      1.220724          0.220556          -0.313395         0.613179   
..          ...               ...                ...              ...   
564    2.015301          0.378365          -0.273318         0.664512   
565    1.494959         -0.691230          -0.394820         0.236573   
566    0.427906         -0.809587           0.350735         0.326767   
567    1.653171          1.430427           3.904848         3.197605   
568   -1.075813         -1.859019          -1.207552        -1.305831   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                2.296076        2.750622                 1.937015  
1                1.087084       -0.243890                 0.281190  
2                1.955000        1.152255                 0.201391  
3                2.175786        6.046041                 4.935010  
4                0.729259       -0.868353                -0.397100  
..                    .

In [8]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data,test_size=0.2)


In [9]:
trainX=train.drop("diagnosis",axis=1)
trainY=train.loc[:,"diagnosis"]
testX=test.drop("diagnosis",axis=1)
testY=test.loc[:,"diagnosis"]

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB

model1=LogisticRegression()
model2=LinearSVC()
model3=GaussianNB()

model1.fit(trainX,trainY)
model2.fit(trainX,trainY)
model3.fit(trainX,trainY)

tahminler1=model1.predict(testX)
tahminler2=model2.predict(testX)
tahminler3=model3.predict(testX)




/home/eray/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


In [12]:
from sklearn.metrics import classification_report,confusion_matrix

confusion_matrix(testY,tahminler1)


array([[57,  0],
       [ 3, 54]])

In [13]:
confusion_matrix(testY,tahminler2)


array([[56,  1],
       [ 2, 55]])

In [14]:
confusion_matrix(testY,tahminler3)

array([[54,  3],
       [ 9, 48]])

In [16]:
print(classification_report(testY,tahminler1))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        57
           1       1.00      0.95      0.97        57

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.98      0.97      0.97       114



In [17]:
print(classification_report(testY,tahminler2))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97        57
           1       0.98      0.96      0.97        57

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [19]:
print(classification_report(testY,tahminler3))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90        57
           1       0.94      0.84      0.89        57

    accuracy                           0.89       114
   macro avg       0.90      0.89      0.89       114
weighted avg       0.90      0.89      0.89       114

