In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.svm import LinearSVC

In [15]:
data=pd.read_csv("trainAndTest.csv")
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M     1.097064     -2.073335        1.269934   0.984375   
1           M     1.829821     -0.353632        1.685955   1.908708   
2           M     1.579888      0.456187        1.566503   1.558884   
3           M    -0.768909      0.253732       -0.592687  -0.764464   
4           M     1.750297     -1.151816        1.776573   1.826229   
..        ...          ...           ...             ...        ...   
564         M     2.110995      0.721473        2.060786   2.343856   
565         M     1.704854      2.085134        1.615931   1.723842   
566         M     0.702284      2.045574        0.672676   0.577953   
567         M     1.838341      2.336457        1.982524   1.735218   
568         B    -1.808401      1.221792       -1.814389  -1.347789   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           1.568466          3.283515        2.652874             2.532475   
1          -0.826962         -0.487072       -0.023846             0.548144   
2           0.942210          1.052926        1.363478             2.037231   
3           3.283553          3.402909        1.915897             1.451707   
4           0.280372          0.539340        1.371011             1.428493   
..               ...               ...             ...                  ...   
564         1.041842          0.219060        1.947285             2.320965   
565         0.102458         -0.017833        0.693043             1.263669   
566        -0.840484         -0.038680        0.046588             0.105777   
567         1.525767          3.272144        3.296944             2.658866   
568        -3.112085         -1.150752       -1.114873            -1.261820   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         2.217515  ...      1.886690      -1.359293         2.303601   
1         0.001392  ...      1.805927      -0.369203         1.535126   
2         0.939685  ...      1.511870      -0.023974         1.347475   
3         2.867383  ...     -0.281464       0.133984        -0.249939   
4        -0.009560  ...      1.298575      -1.466770         1.338539   
..             ...  ...           ...            ...              ...   
564      -0.312589  ...      1.901185       0.117700         1.752563   
565      -0.217664  ...      1.536720       2.047399         1.421940   
566      -0.809117  ...      0.561361       1.374854         0.579001   
567       2.137194  ...      1.961239       2.237926         2.303601   
568      -0.820070  ...     -1.410893       0.764190        -1.432735   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2.001237          1.307686           2.616665         2.109526   
1      1.890489         -0.375612          -0.430444        -0.146749   
2      1.456285          0.527407           1.082932         0.854974   
3     -0.550021          3.394275           3.893397         1.989588   
4      1.220724          0.220556          -0.313395         0.613179   
..          ...               ...                ...              ...   
564    2.015301          0.378365          -0.273318         0.664512   
565    1.494959         -0.691230          -0.394820         0.236573   
566    0.427906         -0.809587           0.350735         0.326767   
567    1.653171          1.430427           3.904848         3.197605   
568   -1.075813         -1.859019          -1.207552        -1.305831   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                2.296076        2.750622                 1.937015  
1                1.087084       -0.243890                 0.281190  
2                1.955000        1.152255                 0.201391  
3                2.175786        6.046041                 4.935010  
4                0.729259       -0.868353                -0.397100  
..                    ...         

In [16]:
encoder=LabelEncoder()
data["diagnosis"]=encoder.fit_transform(data["diagnosis"])
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1     1.097064     -2.073335        1.269934   0.984375   
1            1     1.829821     -0.353632        1.685955   1.908708   
2            1     1.579888      0.456187        1.566503   1.558884   
3            1    -0.768909      0.253732       -0.592687  -0.764464   
4            1     1.750297     -1.151816        1.776573   1.826229   
..         ...          ...           ...             ...        ...   
564          1     2.110995      0.721473        2.060786   2.343856   
565          1     1.704854      2.085134        1.615931   1.723842   
566          1     0.702284      2.045574        0.672676   0.577953   
567          1     1.838341      2.336457        1.982524   1.735218   
568          0    -1.808401      1.221792       -1.814389  -1.347789   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           1.568466          3.283515        2.652874             2.532475   
1          -0.826962         -0.487072       -0.023846             0.548144   
2           0.942210          1.052926        1.363478             2.037231   
3           3.283553          3.402909        1.915897             1.451707   
4           0.280372          0.539340        1.371011             1.428493   
..               ...               ...             ...                  ...   
564         1.041842          0.219060        1.947285             2.320965   
565         0.102458         -0.017833        0.693043             1.263669   
566        -0.840484         -0.038680        0.046588             0.105777   
567         1.525767          3.272144        3.296944             2.658866   
568        -3.112085         -1.150752       -1.114873            -1.261820   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         2.217515  ...      1.886690      -1.359293         2.303601   
1         0.001392  ...      1.805927      -0.369203         1.535126   
2         0.939685  ...      1.511870      -0.023974         1.347475   
3         2.867383  ...     -0.281464       0.133984        -0.249939   
4        -0.009560  ...      1.298575      -1.466770         1.338539   
..             ...  ...           ...            ...              ...   
564      -0.312589  ...      1.901185       0.117700         1.752563   
565      -0.217664  ...      1.536720       2.047399         1.421940   
566      -0.809117  ...      0.561361       1.374854         0.579001   
567       2.137194  ...      1.961239       2.237926         2.303601   
568      -0.820070  ...     -1.410893       0.764190        -1.432735   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2.001237          1.307686           2.616665         2.109526   
1      1.890489         -0.375612          -0.430444        -0.146749   
2      1.456285          0.527407           1.082932         0.854974   
3     -0.550021          3.394275           3.893397         1.989588   
4      1.220724          0.220556          -0.313395         0.613179   
..          ...               ...                ...              ...   
564    2.015301          0.378365          -0.273318         0.664512   
565    1.494959         -0.691230          -0.394820         0.236573   
566    0.427906         -0.809587           0.350735         0.326767   
567    1.653171          1.430427           3.904848         3.197605   
568   -1.075813         -1.859019          -1.207552        -1.305831   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                2.296076        2.750622                 1.937015  
1                1.087084       -0.243890                 0.281190  
2                1.955000        1.152255                 0.201391  
3                2.175786        6.046041                 4.935010  
4                0.729259       -0.868353                -0.397100  
..                    .

In [17]:
train,test=train_test_split(data,test_size=0.2)
test

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
6            1     1.170908      0.160649        1.138125   1.095295   
201          1     0.969258      0.007063        0.952769   0.843876   
26           1     0.128576      0.521345        0.224115  -0.028694   
255          1    -0.047513     -0.521181       -0.022203  -0.149284   
103          0    -1.207427      0.025680       -1.154110  -1.014176   
..         ...          ...           ...             ...        ...   
279          0    -0.078755     -0.956343       -0.122707  -0.191946   
175          0    -1.549664     -1.126219       -1.546652  -1.216392   
383          0    -0.493416     -0.421117       -0.466645  -0.546037   
292          0    -0.334368     -0.760869       -0.363670  -0.401556   
321          1     1.713375      0.086183        1.611812   1.760815   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
6          -0.123136          0.088295        0.300072             0.646935   
201        -0.475405          0.292971        0.185822             0.669634   
26          0.643316          1.562720        0.674211             1.003666   
255         0.942210          0.446478        0.114133             0.091333   
103         0.294605         -0.139691       -0.342240            -0.480520   
..               ...               ...             ...                  ...   
279        -0.085419         -0.520426       -0.552536            -0.304605   
175        -0.354424         -1.167051       -1.114873            -1.261820   
383         0.557917          0.480591       -0.375134            -0.518953   
292         0.294605         -0.472100       -0.342114            -0.392562   
321        -1.150054         -0.354411        0.335226             0.731023   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
6        -0.064325  ...      1.368983       0.322883         1.368325   
201      -1.115796  ...      0.859560       0.026507         0.960259   
26        1.607807  ...      0.279729       1.226666         0.450921   
255       0.351883  ...      0.025018      -0.587414         0.024984   
103       0.486968  ...     -1.140857       0.187723        -1.043732   
..             ...  ...           ...            ...              ...   
279       1.089373  ...     -0.266969      -0.641152        -0.264832   
175      -0.327193  ...     -1.451067      -1.406518        -1.456564   
383      -0.119089  ...     -0.432635      -0.414799        -0.358360   
292      -0.297985  ...     -0.523751      -0.935900        -0.549585   
321       0.424902  ...      1.406258      -0.431084         1.278968   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
6      1.275220          0.518640           0.021215         0.509552   
201    0.630066          0.251241           0.558117         0.377141   
26     0.028684          0.882478           2.608395         1.351518   
255   -0.095952          0.825491           0.457607         0.233695   
103   -0.913030          1.031520          -0.153087        -0.037365   
..          ...               ...                ...              ...   
279   -0.370187         -0.607942          -0.520776        -0.607311   
175   -1.092337         -0.708765          -1.168557        -1.305831   
383   -0.492362          0.452886           0.668169         0.232255   
292   -0.518906          0.698367          -0.301944        -0.230706   
321    1.364873         -1.182192          -0.639734        -0.055596   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
6                1.196716        0.262476                -0.014730  
201              1.207374        0.044075                -0.292364  
26               2.367641        2.205430                 2.413591  
255              0.347072        0.270565                -0.242489  
103             -0.260622       -0.450966                 0.052877  
..                    .

In [18]:
xTrain=train.drop("diagnosis",axis=1)
yTrain=train.loc[:,"diagnosis"]

In [19]:
xTest=test.drop("diagnosis",axis=1)
yTest=test.loc[:,"diagnosis"]

In [22]:
model=LogisticRegression()
model.fit(xTrain,yTrain)


LogisticRegression()

In [23]:
tahminler=model.predict(xTest)
tahminler

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1])

In [24]:
confusion_matrix(yTest,tahminler)

array([[68,  1],
       [ 5, 40]])

In [26]:
print(classification_report(yTest,tahminler))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96        69
           1       0.98      0.89      0.93        45

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



In [27]:
model2=LinearSVC()
model2.fit(xTrain,yTrain)


/home/eray/anaconda3/lib/python3.11/site-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


LinearSVC()

In [28]:
tahminler2=model2.predict(xTest)

In [29]:
tahminler2

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1])

In [30]:
confusion_matrix(yTest,tahminler2)

array([[65,  4],
       [ 3, 42]])

In [32]:
print(classification_report(yTest,tahminler2))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        69
           1       0.91      0.93      0.92        45

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.94       114
weighted avg       0.94      0.94      0.94       114

